### ISSUE TITLE
Reoccurring error in appsource-verify CI test (servicemesh)

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/terraform-google-enterprise-application#158]
Last successful [CI test](https://pantheon.corp.google.com/cloud-build/builds/e2aa948b-7751-4ef1-bb0a-7d577764b2fe?project=cloud-foundation-cicd&e=13803378&mods=prod) started May 24, 2024, 9:16:13 PM: 

Initial observed failure [CI test](https://pantheon.corp.google.com/cloud-build/builds/8c4ade73-a123-4793-be2c-40e7381c5d3a?project=cloud-foundation-cicd&e=13803378&mods=prod) started May 26, 2024, 8:00:46 PM

The error presents during `appsource-verify` as:
```
"resource mapping not found for name: \"frontend\" namespace: \"\" from \"/workspace/stable/manifest.yaml\": no matches for kind \"DestinationRule\" in version \"networking.istio.io/v1beta1\"\nensure CRDs are installed first\nresource mapping not found for name: \"frontend\" namespace: \"\" from \"/workspace/stable/manifest.yaml\": no matches for kind \"VirtualService\" in version \"networking.istio.io/v1beta1\"\nensure CRDs are installed first\n"
```

This is because `servicemesh` failed to install on the cluster(s) during the earlier stages and so the CRDs are not present:
```
gcloud container hub features describe servicemesh
createTime: '2024-05-29T13:54:40.160204448Z'
fleetDefaultMemberConfig:
  mesh:
    management: MANAGEMENT_AUTOMATIC
membershipSpecs:
  projects/361776789833/locations/us-central1/memberships/cluster-us-central1-development:
    mesh:
      management: MANAGEMENT_AUTOMATIC
    origin:
      type: USER
membershipStates:
  projects/{}/locations/us-central1/memberships/cluster-us-central1-development:
    servicemesh:
      controlPlaneManagement:
        details:
        - code: REVISION_STALLED
          details: 'Failed to provision: asm-managed'
        state: STALLED
      dataPlaneManagement:
        details:
        - code: MANAGED_CONTROL_PLANE_REQUIRED
          details: Requires active managed control plane.
        state: FAILED_PRECONDITION
    state:
      code: ERROR
      description: 'Revision reporting unhealthy: asm-managed. Please visit https://cloud.google.com/service-mesh/docs/troubleshooting/troubleshoot-intro
        for details.'
      updateTime: '2024-05-29T14:03:08.084756592Z'
name: projects/{}/locations/global/features/servicemesh
resourceState:
  state: ACTIVE
spec: {}
updateTime: '2024-05-29T14:02:01.617696060Z'
```

```
kubectl describe controlplanerevision asm-managed -n istio-system
Name:         asm-managed
Namespace:    istio-system
Labels:       app.kubernetes.io/created-by=mesh.googleapis.com
              istio.io/owned-by=mesh.googleapis.com
              mesh.cloud.google.com/managed-cni-enabled=true
Annotations:  mesh.cloud.google.com/proxy: {"managed":"true"}
API Version:  mesh.cloud.google.com/v1beta1
Kind:         ControlPlaneRevision
Metadata:
  Creation Timestamp:  2024-05-30T17:17:17Z
  Generation:          1
  Resource Version:    86615
  UID:                 {}
Spec:
  Channel:  regular
  Type:     managed_service
Status:
  Conditions:
    Last Transition Time:  2024-05-30T18:48:51Z
    Message:               The provisioning process has not completed successfully
    Reason:                NotProvisioned
    Status:                False
    Type:                  Reconciled
    Last Transition Time:  2024-05-30T18:48:51Z
    Message:               Provisioning has finished
    Reason:                ProvisioningFinished
    Status:                True
    Type:                  ProvisioningFinished
    Last Transition Time:  2024-05-30T18:48:51Z
    Message:               An internal error has occurred. Please contact customer support. This will be retried within 15 minutes.
    Reason:                ProvisioningFailed
    Status:                True
    Type:                  Stalled
Events:                    <none>
```

The relevant error message appears to be `An internal error has occurred. Please contact customer support. This will be retried within 15 minutes.`

**Comment by apeabody** [comment]
Managed Service Mesh: `Failed to provision: asm-managed`

**Comment by apeabody** [comment]
TODO: In addition to `MANAGEMENT_AUTOMATIC`, we should also validate the membership states:

```
gcloud container hub features describe servicemesh
createTime: '2024-05-29T13:54:40.160204448Z'
fleetDefaultMemberConfig:
  mesh:
    management: MANAGEMENT_AUTOMATIC
membershipSpecs:
  projects/361776789833/locations/us-central1/memberships/cluster-us-central1-development:
    mesh:
      management: MANAGEMENT_AUTOMATIC
    origin:
      type: USER
membershipStates:
  projects/{}/locations/us-central1/memberships/cluster-us-central1-development:
    servicemesh:
      controlPlaneManagement:
        details:
        - code: REVISION_STALLED
          details: 'Failed to provision: asm-managed'
        state: STALLED
      dataPlaneManagement:
        details:
        - code: MANAGED_CONTROL_PLANE_REQUIRED
          details: Requires active managed control plane.
        state: FAILED_PRECONDITION
    state:
      code: ERROR
      description: 'Revision reporting unhealthy: asm-managed. Please visit https://cloud.google.com/service-mesh/docs/troubleshooting/troubleshoot-intro
        for details.'
      updateTime: '2024-05-29T14:03:08.084756592Z'
name: projects/{}/locations/global/features/servicemesh
resourceState:
  state: ACTIVE
spec: {}
updateTime: '2024-05-29T14:02:01.617696060Z'
````

https://github.com/GoogleCloudPlatform/terraform-google-enterprise-application/blob/main/test/integration/fleetscope/fleetscope_test.go#L103

CC: @amandakarina
